// <auto-generated />
using FirstAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstAPI.Migrations
{
    [DbContext(typeof(FirstAPIContext))]
    partial class FirstAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("FirstAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearPublished")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Adam Mickiewicz",
                            Title = "Pan Tadeusz",
                            YearPublished = 1834
                        },
                        new
                        {
                            Id = 2,
                            Author = "Adam Mickiewicz",
                            Title = "Dziady",
                            YearPublished = 1822
                        },
                        new
                        {
                            Id = 3,
                            Author = "Juliusz Slowacki",
                            Title = "Kordian",
                            YearPublished = 1834
                        },
                        new
                        {
                            Id = 4,
                            Author = "Joseph Conrad",
                            Title = "Jadro Ciemnosci",
                            YearPublished = 1902
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
